name: kdbx
description: KeepassX format implementation in pure dart. (kdbx 3.x and 4.x support).
version: 0.5.20+0
homepage: https://github.com/kee-org/kdbx.dart
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  logging: ^1.2.0
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  xml: '>=6.4.2 <7.0.0'
  uuid: ^3.0.7
  meta: ^1.9.1
  clock: ^1.1.1
  convert: ^3.1.1
  isolate: ^2.1.1
  path: ^1.8.3
  quiver: ^3.2.1
  archive: ^3.4.9
  #supercharged_dart: ^2.1.1
  synchronized: ^3.1.0

  collection: '>=1.15.0 <2.0.0'

  # required for bin/
  args: ^2.4.2
  logging_appenders: ^1.2.0
  argon2_ffi_base: ^1.1.1

dev_dependencies:
  flutter_lints: ">=2.0.0 <3.0.0"
  test: ^1.24.9
  fake_async: ^1.3.1
