name: kdbx
description: KeepassX format implementation in pure dart. (kdbx 3.x and 4.x support).
version: 0.5.13+6
homepage: https://github.com/kee-org/kdbx.dart
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  crypto: ^3.0.1
  pointycastle: ^3.4.0
  xml: ^5.3.1
  uuid: ^3.0.5
  meta: ^1.7.0
  clock: ^1.1.0
  convert: ^3.0.1
  isolate: ^2.1.1
  path: ^1.8.0
  quiver: ^3.0.1+1
  archive: ^3.1.6
  supercharged_dart: ^2.1.1
  synchronized: ^3.0.0

  collection: ^1.15.0

  # required for bin/
  args: ^2.3.0
  logging_appenders: ^1.0.0
  argon2_ffi_base: ^1.1.0+1

dev_dependencies:
  flutter_lints: ">=1.0.4 <2.0.0"
  test: ^1.17.10
  fake_async: ^1.2.0
