name: kdbx
description: KeepassX format implementation in pure dart. (kdbx 3.x and 4.x support).
version: 0.5.7+3
homepage: https://github.com/authpass/kdbx.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  flutter:
#    sdk: flutter
#  path: ^1.6.0
  logging: ^1.0.1
  crypto: ^3.0.1
  pointycastle: ^3.0.1
  xml: ^5.1.0
  uuid: ^3.0.4
  meta: ^1.3.0
  clock: ^1.1.0
  convert: ^3.0.0
  isolate: #'>=2.0.3 <3.0.0'
    git:
      url: https://github.com/2ZeroSix/isolate
      ref: master
  path: ^1.8.0
  quiver: ^3.0.1
  archive: ^3.1.2
  supercharged_dart: ^2.0.0
  synchronized: ^3.0.0

  collection: ^1.15.0

  # required for bin/
  args: ^2.0.0
  logging_appenders: ^1.0.0
  argon2_ffi_base: ^1.0.0+2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  fake_async: ^1.2.0

# dependency_overrides:
#   logging: '>=1.0.0'