name: Dart CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-2019', 'macos-latest']
        sdk: ['stable', 'beta']

      fail-fast: false
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    - uses: dart-lang/setup-dart@v1
      with:
            sdk: ${{ matrix.sdk }}
    - run: |
        which dart
        codesign --remove-signature $(which dart)
      if: startsWith(matrix.os, 'macos')
    - name: Install dependencies
      run: dart pub get
    - name: Run tests
      run: dart run test
